<?php

namespace WhatsTheMusic\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository
{
    public function getAll($limit)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()->select('q')->from('WhatsTheMusic\Entity\Quiz', 'q');
        $qb->setMaxResults($limit);

        $quizzes = $qb->getQuery()->getArrayResult();

        return $quizzes;
    }
}
